# Generated by Django 6.0.2 on 2026-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_torneios/'),
        ),
        migrations.AddField(
            model_name='torneio',
            name='status',
            field=models.CharField(choices=[('aberto', 'Inscrições Abertas'), ('andamento', 'Em Andamento'), ('encerrado', 'Encerrado')], default='aberto', max_length=20),
        ),
    ]
