# Generated by Django 6.0.2 on 2026-02-05 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0002_torneio_imagem_capa_torneio_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='jogadores/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='torneio',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='torneios', to='torneios.jogador'),
        ),
    ]
