# Generated by Django 6.0.2 on 2026-02-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0003_jogador_torneio_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='rating',
        ),
        migrations.AddField(
            model_name='jogador',
            name='categoria',
            field=models.CharField(choices=[('U8', 'Sub-08'), ('U10', 'Sub-10'), ('U12', 'Sub-12'), ('U14', 'Sub-14'), ('U16', 'Sub-16'), ('U18', 'Sub-18'), ('U20', 'Sub-20'), ('S60', 'Sênior 60+'), ('ABERTO', 'Aberto')], default='ABERTO', max_length=10),
        ),
        migrations.AddField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jogador',
            name='rating_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jogador',
            name='username_chesscom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuário Chess.com'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='username_lichess',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuário Lichess.org'),
        ),
    ]
