# Generated by Django 6.0.2 on 2026-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0004_remove_jogador_foto_perfil_remove_jogador_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='id_cbx',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID CBX'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='rating_cbx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating CBX'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='rating_fide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='username_chesscom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário Chess.com'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='username_lichess',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário Lichess.org'),
        ),
    ]
