# Generated by Django 6.0.2 on 2026-02-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0005_jogador_id_cbx_jogador_rating_cbx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='rating_local',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating Local'),
        ),
    ]
