# Generated by Django 6.0.2 on 2026-02-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0006_jogador_genero_jogador_rating_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterField(
            model_name='torneio',
            name='status',
            field=models.CharField(choices=[('BREVE', 'Confirmado (Inscrições em breve)'), ('ABERTO', 'Inscrições Abertas'), ('ANDAMENTO', 'Em Andamento / Inscrições Encerradas'), ('ENCERRADO', 'Torneio Finalizado')], default='BREVE', max_length=20),
        ),
    ]
