# Generated by Django 6.0.2 on 2026-02-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0007_alter_jogador_options_alter_torneio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='status',
            field=models.CharField(choices=[('CONFIRMAR', 'A Confirmar'), ('BREVE', 'Confirmado (Inscrições em breve)'), ('ABERTO', 'Inscrições Abertas'), ('ANDAMENTO', 'Em Andamento / Inscrições Encerradas'), ('ENCERRADO', 'Torneio Finalizado')], default='BREVE', max_length=20),
        ),
    ]
